// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmmtiwwkckghojetbehp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttbXRpd3drY2tnaG9qZXRiZWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzE2OTEsImV4cCI6MjA2NzAwNzY5MX0.ceBW2SXZ3aagsK2POyz7-UQZfwekaCWb2mja6bvV7dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});